services:
    my.firebase_listner:
        class: Procash\GestionBundle\EventListener\FirebaseUpdate
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postPersist }