<?php

namespace Procash\AdministrationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GestionVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionVersionRepository extends EntityRepository
{
    public function getGestionVersionActif() {
        $qb = $this->createQueryBuilder('gv')
                ->where('gv.actif = 1');
         $qry = $qb->getQuery();

        return $qry->getResult();   
    }
  
}
