<?php

namespace Procash\AdministrationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MotifFermetureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotifFermetureRepository extends EntityRepository
{
    
    public function getMotifsFermetures() {
        $qB = $this->createQueryBuilder('mf');
        $qB->where($qB->expr()->isNull('mf.dateSuppression'));
        
        $qry = $qB->getQuery();
        
        return $qry->getResult();
    }
    
}
