<?php

namespace Procash\AdministrationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
 {

    public function getProduits() {
        $qB = $this->createQueryBuilder('p');
        $qB->where($qB->expr()->isNull('p.dateSuppression'));

        $qry = $qB->getQuery();

        return $qry->getResult();
    }

}
