<?php

namespace Procash\AdministrationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReseauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReseauRepository extends EntityRepository
{
}
