<?php

namespace Procash\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function getListeUserCollecteur() {
        $qb = $this->createQueryBuilder("u");
        $qb->where('u.profilCollecteur = true');
        $qb->andWhere('u.dateSuppression IS NULL');

        return $qb->getQuery()->getResult();
    }

    public function getUtilisateurParFiltre($filtre) {
        $qb = $this->createQueryBuilder("u");
        $qb->where('u.dateSuppression IS NULL');
        if ($filtre['utilisateur'] != "") {
            $qb->andWhere('u.id = :utilisateur');
            $qb->setParameter('utilisateur', $filtre['utilisateur']);
        }
        if ($filtre['profil'] != "") {
            $qb->innerJoin('u.profil', 'p');
            $qb->andWhere('p.id = :profil');
            $qb->setParameter('profil', $filtre['profil']);
        }
        if ($filtre['email'] != "") {
            $qb->andWhere('u.email = :email');
            $qb->setParameter('email', $filtre['email']);
        }
        if ($filtre['date_creation'] != "") {
            $dc = explode('/',$filtre['date_creation']);
            $d = $dc[2].'-'.$dc[1].'-'.$dc[0];
            $date = new \DateTime($d);
            $from = new \DateTime($date->format('Y-m-d') . ' 00:00:00');
            $to = new \DateTime($date->format('Y-m-d'). ' 23:59:59');
            $qb->andWhere('u.dateCreation BETWEEN :from AND :to');
            $qb->setParameter('to', $to);
            $qb->setParameter('from', $from);
        }        
        $qr = $qb->getQuery();
        return $qr->getResult();
    }

}
