security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER: ROLE_ALLOWED_TO_SWITCH
        ROLE_ADMIN: [ROLE_USER, ROLE_EVENT_CREATE ]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            anonymous:    true
            
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                username_parameter:       _username
                password_parameter:       _password
                require_previous_session: false
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt: ~
                    
        main:
            pattern: ^/
            anonymous:    true
            provider: fos_userbundle
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                always_use_default_target_path: false
                use_referer: true
                always_use_default_target_path: false
                csrf_provider: security.csrf.token_manager 
                success_handler: redirect.after.login
            logout:
                path:   fos_user_security_logout
                target: /login
            remember_me:
                key:    %secret% # %secret% est un paramètre de parameters.yml
            switch_user: ~
            anonymous:    true
            
    access_control:
        - { path: ^/administration, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/referentiel, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rest, roles: IS_AUTHENTICATED_ANONYMOUSLY }



