<?php

namespace Procash\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HistoriqueRegulRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueRegulRepository extends EntityRepository
{
}
