<?php

namespace Procash\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SaisiFermetureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisiFermetureRepository extends EntityRepository {

    public function getMotifFermeturesFiltre($filtre) {
        $qb = $this->createQueryBuilder("mf");
        $qb->where('mf.dateSuppression IS NULL');
        if ($filtre['client'] != "") {
            $qb->innerJoin('mf.client', 'cl');
            $qb->andWhere('cl.id = :client');
            $qb->setParameter('client', $filtre['client']);
        }
        if ($filtre['date_debut'] != "" && $filtre['date_fin']) {
            $dd = explode('/', $filtre['date_debut']);
            $df = explode('/', $filtre['date_fin']);
            $ddString = $dd[2] . '-' . $dd[1] . '-' . $dd[0];
            $dfString = $df[2] . '-' . $df[1] . '-' . $df[0];
            $dateDD = new \DateTime($ddString);
            $dateDF = new \DateTime($dfString);
            $dateDDD = new \DateTime($dateDD->format('Y-m-d') . ' 00:00:00');
            $dateDFD = new \DateTime($dateDF->format('Y-m-d') . ' 23:59:59');
            $qb->andWhere('mf.dateDebutFermeture >= :dd AND mf.dateFinFermeture <= :df');
            $qb->setParameter('dd', $dateDDD);
            $qb->setParameter('df', $dateDFD);
        }
        if ($filtre['date_debut'] != "") {
            $dd = explode('/', $filtre['date_debut']);
            $ddString = $dd[2] . '-' . $dd[1] . '-' . $dd[0];
            $dateDD = new \DateTime($ddString);
            $dateDD1 = new \DateTime($dateDD->format('Y-m-d') . ' 00:00:00');
            $dateDD2 = new \DateTime($dateDD->format('Y-m-d') . ' 23:59:59');
            $qb->andWhere('mf.dateDebutFermeture >= :dd1 AND mf.dateDebutFermeture <= :dd2');
            $qb->setParameter('dd1', $dateDD1);
            $qb->setParameter('dd2', $dateDD2);
        }
        
        if ($filtre['date_fin'] != "") {
            $df = explode('/', $filtre['date_fin']);
            $dfString = $df[2] . '-' . $df[1] . '-' . $df[0];
            $dateDF = new \DateTime($dfString);
            $dateDF1 = new \DateTime($dateDF->format('Y-m-d') . ' 00:00:00');
            $dateDF2 = new \DateTime($dateDF->format('Y-m-d') . ' 23:59:59');
            $qb->andWhere('mf.dateFinFermeture >= :df1 AND mf.dateFinFermeture <= :df2');
            $qb->setParameter('df1', $dateDF1);
            $qb->setParameter('df2', $dateDF2);
        }

        if ($filtre['motif'] != "") {
            $qb->innerJoin('mf.motifFermeture', 'm');
            $qb->andWhere('m.id = :motif');
            $qb->setParameter('motif', $filtre['motif']);
        }
        $qr = $qb->getQuery();
        return $qr->getResult();
    }

}
